[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
subscription_contract = "BvuGGNocQNB8ybd6mYjy9HScPc3hf2bUWnQjVzbmDRCF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.solana.com"
wallet = "~/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
